// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechSpire.infra.Dbcontext;

#nullable disable

namespace TechSpire.infra.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    partial class AppDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.ApplicataionUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("CompletedLessonIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleUrl = "https://www.w3schools.com/python/",
                            Description = "A beginner's guide to Python programming language.",
                            ImageUrl = "",
                            StageId = 1,
                            Title = "Introduction to Python"
                        },
                        new
                        {
                            Id = 2,
                            ArticleUrl = "https://docs.python.org/3/tutorial/index.html",
                            Description = "Learn the basics of Pyhton, the language of the web.",
                            ImageUrl = "",
                            StageId = 1,
                            Title = "Getting Started with Pyhton"
                        },
                        new
                        {
                            Id = 3,
                            ArticleUrl = "https://realpython.com/python-basics/",
                            Description = "Go From Basic to Intermediate Python Knowledge",
                            ImageUrl = "",
                            StageId = 1,
                            Title = "Basics For Python"
                        },
                        new
                        {
                            Id = 4,
                            ArticleUrl = "https://www.geeksforgeeks.org/python-data-structures-and-algorithms/",
                            Description = "Learn about lists, tuples, sets, and dictionaries in Python.",
                            ImageUrl = "",
                            StageId = 2,
                            Title = "Python Data Structures"
                        },
                        new
                        {
                            Id = 5,
                            ArticleUrl = "https://www.geeksforgeeks.org/python-oops-concepts/",
                            Description = "Understanding functions and modules in Python.",
                            ImageUrl = "",
                            StageId = 2,
                            Title = "Python Functions and Modules"
                        },
                        new
                        {
                            Id = 6,
                            ArticleUrl = "https://realpython.com/python3-object-oriented-programming/",
                            Description = "An introduction to OOP concepts in Python.",
                            ImageUrl = "",
                            StageId = 2,
                            Title = "Python Object-Oriented Programming"
                        },
                        new
                        {
                            Id = 7,
                            ArticleUrl = "https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files",
                            Description = "Learn how to read and write files in Python.",
                            ImageUrl = "",
                            StageId = 3,
                            Title = "Python File Handling"
                        },
                        new
                        {
                            Id = 8,
                            ArticleUrl = "https://www.geeksforgeeks.org/advanced-python-tutorials/",
                            Description = "Python language is a very versatile language and it is used in many technical fields.",
                            ImageUrl = "",
                            StageId = 3,
                            Title = "Python such as Data Science, Artificial Intelligence and Robotics"
                        },
                        new
                        {
                            Id = 9,
                            ArticleUrl = "https://www.w3schools.com/python/python_ml_getting_started.asp",
                            Description = "In this tutorial we will go back to mathematics and study statistics.",
                            ImageUrl = "",
                            StageId = 3,
                            Title = "Python in Machine Learning"
                        });
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Fav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Favs");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "In this lesson, we will cover the basics of Python programming, including syntax, variables, and data types. You will learn how to write your first Python program and understand the structure of Python code.  What can Python do?  Python can be used on a server to create web applications.\r\nPython can be used alongside software to create workflows.\r\nPython can connect to database systems. It can also read and modify files.\r\nPython can be used to handle big data and perform complex mathematics.\r\nPython can be used for rapid prototyping, or for production-ready software development.\r\n",
                            StageId = 1,
                            Title = "Lesson 1 : Introduction to Python"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This lesson will guide you through setting up your Python environment, installing necessary tools, and writing your first Python script. You will also learn about basic input and output operations.\n Many PCs and Macs will have python already installed.\r\n\r\nTo check if you have python installed on a Windows PC, search in the start bar for Python",
                            StageId = 1,
                            Title = "Lesson 2 : Getting Started with Python"
                        },
                        new
                        {
                            Id = 3,
                            Content = "In this lesson, we will explore basic Python concepts such as control flow, loops, and functions. You will learn how to create reusable code blocks and understand the importance of functions in programming.\n Python Quickstart\r\nPython is an interpreted programming language, this means that as a developer you write Python (.py) files in a text editor and then put those files into the python interpreter to be executed.",
                            StageId = 1,
                            Title = "Lesson 3 : Basics of Python"
                        },
                        new
                        {
                            Id = 4,
                            Content = "This lesson will focus on Python syntax, including indentation, comments, and the use of operators. You will learn how to write clean and readable code, which is essential for effective programming.\n Python Indentation\r\nIndentation refers to the spaces at the beginning of a code line.\r\n\r\nWhere in other programming languages the indentation in code is for readability only, the indentation in Python is very important.\r\n\r\nPython uses indentation to indicate a block of code.",
                            StageId = 1,
                            Title = "Lesson 4 : Python Syntax"
                        },
                        new
                        {
                            Id = 5,
                            Content = "In this lesson, we will dive deeper into Python variables and data types. You will learn about different data types such as strings, integers, and lists, and how to manipulate them effectively. \n Variables\r\nVariables are containers for storing data values.\r\n\r\nCreating Variables\r\nPython has no command for declaring a variable.\r\n\r\nA variable is created the moment you first assign a value to it.",
                            StageId = 1,
                            Title = "Lesson 5 : Python Variables and Data Types"
                        },
                        new
                        {
                            Id = 6,
                            Content = "This lesson will introduce you to Python data structures, including lists, tuples, and dictionaries. You will learn how to choose the right data structure for your needs and how to manipulate them effectively.\n Python Data Structures\r\nPython has a set of built-in data structures, such as lists, tuples, sets, and dictionaries.\r\n\r\nThese data structures allow you to store and manipulate collections of data efficiently.",
                            StageId = 2,
                            Title = "Lesson 6 : Python Data Strcture Intro"
                        },
                        new
                        {
                            Id = 7,
                            Content = "In this lesson, we will explore the first data structure in Python: lists. You will learn how to create, access, and manipulate lists, which are essential for storing collections of data.\n Python Lists\r\nLists are used to store multiple items in a single variable.\r\n\r\nA list is created by placing all the items (elements) inside square brackets [], separated by commas.\r\n\r\nList items are ordered, changeable, and allow duplicate values.",
                            StageId = 2,
                            Title = "Lesson 7 : First Data Strcture "
                        },
                        new
                        {
                            Id = 8,
                            Content = "This lesson will introduce you to stacks in Python, which are a type of data structure that follows the Last In First Out (LIFO) principle. You will learn how to implement stacks using lists and understand their applications.\n Python Stacks\r\nA stack is a collection of elements that supports two main operations: push and pop.\r\n\r\nPush adds an element to the top of the stack, while pop removes the top element from the stack.\r\n\r\nStacks are often used in algorithms and data processing tasks.",
                            StageId = 2,
                            Title = "Lesson 8 : Python Stacks "
                        },
                        new
                        {
                            Id = 9,
                            Content = "In this lesson, we will explore queues in Python, which are a type of data structure that follows the First In First Out (FIFO) principle. You will learn how to implement queues using lists and understand their applications.\n Python Queues\r\nA queue is a collection of elements that supports two main operations: enqueue and dequeue.\r\n\r\nEnqueue adds an element to the end of the queue, while dequeue removes the front element from the queue.\r\n\r\nQueues are often used in scheduling and task management scenarios.",
                            StageId = 2,
                            Title = "Lesson 9 : Python Queues"
                        },
                        new
                        {
                            Id = 10,
                            Content = "This lesson will introduce you to linked lists in Python, which are a type of data structure that consists of nodes. You will learn how to create and manipulate linked lists, and understand their advantages over other data structures.\n Python Linked Lists\r\nA linked list is a linear data structure where each element is a separate object, called a node.\r\n\r\nEach node contains a value and a reference (or link) to the next node in the sequence.\r\n\r\nLinked lists are often used in scenarios where dynamic memory allocation is required.",
                            StageId = 2,
                            Title = "Lesson 10 : Python Linked Lists"
                        },
                        new
                        {
                            Id = 11,
                            Content = "In this lesson, we will explore statistical concepts in Python, including mean, median, and mode. You will learn how to calculate these statistics using Python and understand their significance in data analysis.\n Python Mean Median Mode\r\nMean is the average of a set of numbers, calculated by dividing the sum of all numbers by the count of numbers.\r\n\r\nMedian is the middle value in a sorted list of numbers.\r\n\r\nMode is the value that appears most frequently in a dataset.",
                            StageId = 3,
                            Title = "Lesson 11 : Python Mean Median Mode"
                        },
                        new
                        {
                            Id = 12,
                            Content = "This lesson will cover advanced Python topics such as list comprehensions, lambda functions, and error handling. You will learn how to write more efficient and robust Python code.\n Python List Comprehension\r\nList comprehension offers a shorter syntax when you want to create a new list based on the values of an existing list.\r\n\r\nWith list comprehension you can do all this with only one line of code:\r\n\r\nnewlist = [expression for item in iterable if condition == True]\r\n\r\nWhere the expression is the current item in the iteration, but it is also the outcome, which you can manipulate before it ends up like a list item in the new list.",
                            StageId = 3,
                            Title = "Lesson 12 : Python Advanced Topics"
                        },
                        new
                        {
                            Id = 13,
                            Content = "In this lesson, we will introduce you to the basics of machine learning in Python. You will learn about popular libraries such as Scikit-learn and TensorFlow, and how to build simple machine learning models.\n Python Machine Learning Libraries\r\nPython has a rich ecosystem of libraries for machine learning, including Scikit-learn, TensorFlow, and Keras.\r\n\r\nThese libraries provide powerful tools for building and training machine learning models.",
                            StageId = 3,
                            Title = "Lesson 13 : Python Machine Learning Intro"
                        },
                        new
                        {
                            Id = 14,
                            Content = "This lesson will introduce you to the basics of data science in Python. You will learn about libraries such as NumPy and Pandas, which are essential for data manipulation and analysis.\n Python Data Science Libraries\r\nPython has a rich ecosystem of libraries for data science, including NumPy, Pandas, Matplotlib, and Scikit-learn.\r\n\r\nThese libraries provide powerful tools for data manipulation, analysis, and visualization.",
                            StageId = 3,
                            Title = "Lesson 14 : Python Data Science Intro"
                        },
                        new
                        {
                            Id = 15,
                            Content = "In this lesson, we will introduce you to web development in Python. You will learn about popular web frameworks such as Flask and Django, and how to build simple web applications.\n Python Web Development Frameworks\r\nPython has several popular web frameworks, including Flask and Django.\r\n\r\nThese frameworks provide tools and libraries for building web applications quickly and efficiently.",
                            StageId = 3,
                            Title = "Lesson 15 : Python Web Development Intro"
                        });
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A beginner's guide to Python programming language.",
                            ImageUrl = "",
                            PostUrl = "https://harmash.com/tutorials/python/overview",
                            StageId = 1,
                            Title = "Introduction to Python"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Learn the basics of Pyhton, the language of the web.",
                            ImageUrl = "",
                            PostUrl = "https://academy.hsoub.com/files/15-%D8%A7%D9%84%D8%A8%D8%B1%D9%85%D8%AC%D8%A9-%D8%A8%D9%84%D8%BA%D8%A9-%D8%A8%D8%A7%D9%8A%D8%AB%D9%88%D9%86/",
                            StageId = 1,
                            Title = "Getting Started with Pyhton"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Go From Basic to Intermediate Python Knowledge",
                            ImageUrl = "",
                            PostUrl = "https://colab.research.google.com/drive/1LSSOITVzLrLvVN91kppSh1OHm3CU1Esy?authuser=0#scrollTo=hU-QtmhQo2AN",
                            StageId = 1,
                            Title = "Basics For Python"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Learn about lists, tuples, sets, and dictionaries in Python.",
                            ImageUrl = "",
                            PostUrl = "https://elzero.org/everything-about-data-structure/",
                            StageId = 2,
                            Title = "Python Data Structures"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Understanding functions and modules in Python.",
                            ImageUrl = "",
                            PostUrl = "https://www.kholoodtechnotes.net/2024/07/Python-OOP-ClassObject.html?m=1",
                            StageId = 2,
                            Title = "Python OOP "
                        },
                        new
                        {
                            Id = 6,
                            Description = "An introduction to OOP concepts in Python.",
                            ImageUrl = "",
                            PostUrl = "https://academy.hsoub.com/programming/python/%D9%85%D8%AE%D8%AA%D8%B5%D8%B1-%D8%A7%D9%84%D8%A8%D8%B1%D9%85%D8%AC%D8%A9-%D9%83%D8%A7%D8%A6%D9%86%D9%8A%D8%A9-%D8%A7%D9%84%D8%AA%D9%88%D8%AC%D9%87-oop-%D9%88%D8%AA%D8%B7%D8%A8%D9%8A%D9%82%D9%87%D8%A7-%D9%81%D9%8A-%D8%A8%D8%A7%D9%8A%D8%AB%D9%88%D9%86-r1926/",
                            StageId = 2,
                            Title = "Python Object-Oriented Programming"
                        },
                        new
                        {
                            Id = 7,
                            Description = " An introduction about Machine Learning ",
                            ImageUrl = "",
                            PostUrl = "https://uomus.edu.iq/NewDep.aspx?depid=7&newid=14046",
                            StageId = 3,
                            Title = "Python in Machine Learning"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A guide to using Machine Learning in Python.",
                            ImageUrl = "",
                            PostUrl = "https://academy.hsoub.com/programming/artificial-intelligence/%D8%AA%D8%B9%D9%84%D9%85-%D8%A7%D9%84%D8%A2%D9%84%D8%A9/",
                            StageId = 3,
                            Title = "Machine Learning"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Learn how to use python with data science.",
                            ImageUrl = "",
                            PostUrl = "https://www.tomasbeuzen.com/python-programming-for-data-science/README.html",
                            StageId = 3,
                            Title = "Python With Data Science "
                        });
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StangeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StangeId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Beginner Stage"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intermediate stage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Advanced stage"
                        });
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.UserArticleInProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<double>("CompletedPercentage")
                        .HasColumnType("float");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ArticleId");

                    b.ToTable("UserArticleInProgress");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.UserBookInProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<double>("CompletedPercentage")
                        .HasColumnType("float");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("BookId");

                    b.ToTable("UserBookInProgress");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.UserQuizResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CorrectPercentage")
                        .HasColumnType("float");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("WrongPercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("UserQuizResults");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.UsersProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyArticles")
                        .HasColumnType("int");

                    b.Property<int>("DailyBooks")
                        .HasColumnType("int");

                    b.Property<int>("DailyPosts")
                        .HasColumnType("int");

                    b.Property<DateTime>("StudiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsersProgress");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.ApplicataionUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.ApplicataionUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechSpire.Domain.Entities.ApplicataionUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.ApplicataionUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Answer", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.ApplicataionUser", b =>
                {
                    b.OwnsMany("TechSpire.Domain.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Article", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.Stage", "Stage")
                        .WithMany("Articles")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Book", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.Stage", "Stage")
                        .WithMany("Books")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Fav", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.ApplicataionUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.Stage", "Stage")
                        .WithMany("Lessons")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Post", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.Stage", "Stage")
                        .WithMany("Posts")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Question", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.Stage", "Stange")
                        .WithMany("Quizzes")
                        .HasForeignKey("StangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stange");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.UserAnswer", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechSpire.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechSpire.Domain.Entities.ApplicataionUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.UserArticleInProgress", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.ApplicataionUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechSpire.Domain.Entities.Article", "Book")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.UserBookInProgress", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.ApplicataionUser", "AppUser")
                        .WithMany("UserBookInProgresses")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechSpire.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.UserQuizResult", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechSpire.Domain.Entities.ApplicataionUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.UsersProgress", b =>
                {
                    b.HasOne("TechSpire.Domain.Entities.ApplicataionUser", "User")
                        .WithMany("UsersProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.ApplicataionUser", b =>
                {
                    b.Navigation("UserBookInProgresses");

                    b.Navigation("UsersProgresses");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TechSpire.Domain.Entities.Stage", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Books");

                    b.Navigation("Lessons");

                    b.Navigation("Posts");

                    b.Navigation("Quizzes");
                });
#pragma warning restore 612, 618
        }
    }
}
